### ISSUE TITLE
Calling All Witnesses

### ISSUE THREAD

**Issue by aghamidi** [aghamidi/Project#1]
http://www.abuadnan.com.au/Media/Audio/Calling_All_Witnesses_All_In_One.mp3

What is the topic of the lecture (series)? (3-5 sentences. Don't copy the title.)
Why is this topic important according to the lecturer (3-5 sentences)?

**Comment by iqy007** [comment]
Topic of lecture
The lecture talks about Allah's system of Justice
How Allah will judge everyone using witnesses, those witnesses include almost everything Allah created, our limbs, eyes, this earth, angels and his prophet, every deed, word and action will be held to account, nothing more nothing less

Why this is important?
Whatever we do will have to be accounted for, we cannot escape it, we will be the ones who will be reading from our own book of deeds so must be careful and stay away from what Allah has forbidden
