### ISSUE TITLE
Ramadan, the Month of Victory

### ISSUE THREAD

**Issue by aghamidi** [aghamidi/Project#23]
http://www.youtube.com/watch?v=X_owEg5wH9o

What is the topic of the lecture (series)? (3-5 sentences. Don't copy the title.)
Why is this topic important according to the lecturer (3-5 sentences)?

**Comment by IbnAbdullan-AlAthari** [comment]
Asalamu Alaykum,

The link to the description is not working. Seems like the video has been taken down by Youtube.
Ibn Abdullah

**Comment by aghamidi** [comment]
W alaykum alSalaam wa rahmatAllah wa barakatuhu. I'm so sorry for assigning you wrong lectures. Lectures by Abu Adnan will not be hosted on our site. I will in shaa Allah assign you new lectures in a few minutes. Barak Allah feek!
