### ISSUE TITLE
The Rights of the Wife

### ISSUE THREAD

**Issue by aghamidi** [aghamidi/Project#25]
http://www.youtube.com/watch?v=BTi8qON9Izw

What is the topic of the lecture (series)? (3-5 sentences. Don't copy the title.)
Why is this topic important according to the lecturer (3-5 sentences)?

**Comment by IbnAbdullan-AlAthari** [comment]
Asalamu Alaykum,

The link to the description is not working. Seems like the video has been taken down by Youtube.

Ibn Abdullah
